name: Lume Build
description: Build a site using the Lume static site generator
inputs:
  cmd:
    description: Command to build the site
    required: false
    default: deno task build
runs:
  using: "composite"
  steps:
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Cache Deno dependencies
      uses: actions/cache@v4
      with:
        path: |
          _deno_cache
          _cache
        key: ${{ runner.os }}-deno-
    - name: Run build task
      shell: bash
      env:
        DENO_DIR: _deno_cache
      run: |
        ${{ inputs.cmd }}
